const privacyPolicyText = `We understand and respect your desire for privacy.  To that end, we would like you to know how we use the personal information and materials you provide to us.  This notice explains our online information practices, including details about how the information and materials you provide to us will be collected and utilized. 
As used herein, the "App" refers to the App(s) located at Aphrodite www.theaphroditeapp.com its affiliate sites, subdomains, mobile versions, and any associated applications that are owned and/or operated by Aphrodite Love Corp and its affiliates (collectively, “us”, “we” or “Aphrodite”). Your acceptance of this Privacy Policy, and our right to change it, is initiated by those personal activities that you undertake, including, without limitation, the use of our App (the “App” which together with future versions and any other apps developed by Aphrodite shall hereinafter be referred to collectively as the “App”) and/or any websites created by Aphrodite (collectively, the “Website”), subscribing to our newsletter, or providing your information and/or materials to APHRODITE. By using the Apps or Websites, you indicate your acceptance of this Privacy Policy and you consent to our collection and use of the information and materials you share with us. 

If you are not in agreement with this policy, then you agree that you will not use our Website(s). 

By downloading the App or accessing the Website these Privacy Policy terms will automatically apply to you.  You should make sure therefore that you read this Privacy Policy carefully before using the App or the Website. By downloading the App or accessing a website you are acknowledging that you are not allowed to copy, or modify the App or Website, any part of the App or Website, or our trademarks in any way. You acknowledge that you’re not allowed to attempt to extract the source code of the App or the Website, and you also agree that you will not translate the App or material from the Website into other languages, or make derivative versions. The App and the Website and all the trademarks, copyright, database rights and other intellectual property rights related to them, belong to Aphrodite, without limitation.
We reserve the right to change or otherwise update this Privacy Policy at any time. Such changes or updates are effective immediately after we give notice of the change or update, which we may do by revising the “Date of Last Revision” date of this Privacy Policy or by otherwise posting on the Website, or by email or conventional mail, and/or by any other means which provides reasonable notice. Your use of the Website after such notice is posted means that you accept such changes or updates. You agree that APHRODITE shall not be liable to you for any damages that might result from any changes to the Privacy Policy, if any.

At some point, we may wish to update the App(s) and/or Website(s). For example, the Apps may be currently available on Android and iOS.  The requirements for both systems (and for any additional systems we decide to extend the availability of the App to) may change, and you’ll need to download the updates if you want to keep using the Apps. Aphrodite does not promise that it will always update the Apps or Websites so that it is relevant to you and/or works with the iOS/Android version that you have installed on your device. You, however, promise to always accept updates to the application when offered to you.  We note that we reserve the right to cease providing the Apps and/or Websites, and may terminate use of them at any time without giving notice of termination to you. Unless we tell you otherwise, upon any termination, (a) the rights and licenses granted to you in these terms will end; (b) you must stop using the Apps and Websites, and (if needed) delete the Apps from your device.
We (both directly and through our third party vendors who supply web support services) collect personal data when you register for and use the Apps and Websites. This personal data may include, without limitation, your name, phone number, email address, zip code, birthday, pronouns and if you share it with us, your sexual orientation. We may also collect non-personally-identifiable information (such as your IP address or domain, or general and specific information about your use of the Website) both directly and through third parties, including through the use of Web beacons, for purposes of Website administration and to compile aggregate information about usage of the Website. 

The App may store and process personal data and or materials (including, without limitation, documents, photos, audio recordings and film clips) that you have provided to us, in connection with your use of the App and/or Website. You acknowledge that it is your responsibility to keep your phone and access to the App secure. We therefore recommend that you do not jailbreak or root your phone, which is the process of removing software restrictions and limitations imposed by the official operating system of your device. It could make your phone vulnerable to malware/viruses/malicious programs, compromise your phone’s security features and it could mean that the App won’t work properly or at all.
You should be aware that there are certain things that Aphrodite will not take responsibility for. Certain functions of the App will require the App have an active internet connection. The connection can be Wi-Fi, or provided by your mobile network provider, but Aührodite cannot take responsibility for the App not working at full functionality if you don’t have access to Wi-Fi, and you don’t have any of your data allowance left.
If you’re using the App outside of an area with Wi-Fi, you should remember that your terms of the agreement with your mobile network provider will still apply. As a result, you may be charged by your mobile provider for the cost of data or other third party charges for the duration of the connection while accessing the App. In using the App, you’re accepting responsibility for any such charges, including roaming data charges if you use the App outside of your home territory (i.e. region or country) without turning off data roaming. If you are not the bill payer for the device on which you’re using the App, please be aware that we assume and you hereby represent that you will obtain permission from the bill payer for using the App.
Along the same lines, Aphrodite cannot take responsibility for the way you use the App.  For example, you need to make sure that your device stays charged.  If it runs out of battery and you can’t turn it on to avail the service provider, Aphrodite cannot accept responsibility.
With respect to Aphrodite’s responsibility for your use of the App, when you’re using the App, it’s important to bear in mind that although we endeavour to ensure that it is updated and correct at all times, we do rely on third parties to provide information to us so that we can make the App available to you. Aphrodite accepts no liability for any loss, direct or indirect, you may experience as a result of your relying on the functionality, whether we have been assisted by third parties, or not, in our efforts to deliver a quality product.
You note that may be asked for your credit card information in connection with purchases and in some cases services provided by the App and/or Website. In many cases the products and services may be provided by our related third party vendors. When using our App or Website, your credit card information, along with the other personal data you submit to us may be stored in the App or Website database and will in most cases not be deleted.  We may occasionally process, analze and share this information with our business partners as well as third party financial institutions to verify the credit card numbers and to authorize the processing of the transactions based on that information.  Where a third party financial institution or third-party vendor is involved, we encourage you to review all of their published privacy policies and contact them directly should you have questions as they may have privacy terms that differ from this Privacy Policy.  You are free to inquire at any time whether a third-party is receiving or has received your data and we will provide you with answers.

We have implemented appropriate safeguards to help prevent unauthorized access, maintain data security, and to make proper use of the information that we collect. However, no transmission of data over the Internet is guaranteed to be completely secure. Thus, while we strive to protect your personal information, we cannot and do not guarantee the security of any information you provide to us.

To unsubscribe from any communications from us, follow the “unsubscribe” link at the bottom of the email. We try to only send communications to subscribers and supporters who have expressly stated that they are happy for us to do so via their preferred channels, i.e. email, SMS, phone or post.  If you are having problems being removed from a mailing list, please be in touch with us directly.  
 
POLICY FOR USERS

We collect personal information from users of the Website in order to provide users with a personalized online experience and to provide our sister organizations in the App and Website world (our “Affiliates”) with ways to reach the right audience. We may share the personal and aggregate information we collect from you with our Affiliates and business partners and their related sites. On a confidential basis, we may also share personal information with our corporate affiliates, employees and consultants, or with third parties that perform a particular service on our behalf (such as general administration purposes for the App or Website). We may elect to share aggregate information with third parties for various purposes, including, without limitation, advertising and promotional purposes. If all or part of Aphrodite is merged or if whole or partial control is otherwise transferred to another entity, the information you have provided on or through the App or Website may be transferred to such entity as part of that transaction. We may also disclose your personal information in response to legal process, such as a request by law enforcement, a court order or subpoena, or to protect the integrity of the Website if we believe that you or any other users have been a victim of an alleged crime or in the event it is suspected that you have committed unlawful or otherwise harmful acts.

Information submitted to us at the time of registration or submission may be used for marketing and promotional purposes by us.

PURCHASE OF PRODUCTS OR SERVICES FROM THE WEBSITE

If you download our App or access the Website or purchase a product or service via the App or the Website, information may be collected from you, including your credit card and contact information, for transfer to and use by third party and related providers of the product or service. Unless otherwise stated, we do not and shall not have any responsibility in connection with such purchases and all transactions and use of any customer information are the sole responsibility of the product/service provider. Be sure to review the product/service provider's privacy policy and contact them directly if you have any questions. They may have privacy terms that differ from our Privacy Policy.

LINKS TO THIRD PARTY SITES

The App and Website may contain links to other sites. Please be aware that Aphrodite is not responsible for the privacy practices of such other sites. We encourage our users to be aware when they leave the App or Website and to read the privacy statements of each and every different App and Website that collects personally identifiable information. This privacy statement applies solely to information collected by the Aphrodite App and Website.

THIRD PARTY ADVERTISING

We may use third-party advertising companies and advertising networks to serve ads to you on our behalf when you use the App or visit the Website. These companies may use information (including your name, address, email address, telephone number and employment history) about your usage of the App or visits to the Website in order to provide advertisements about topics or goods or services we believe may be of interest to you.

USE OF IP ADDRESSES

An IP address is a number that is automatically assigned to your computer by your Internet service provider whenever you log on to the Web. Web servers automatically identify your computer by its IP address, so when a user uses the App or requests pages from the Website, our servers log the user's IP address. The IP addresses of our users are collected for the purposes of system administration and to report aggregate information to our advertisers, our corporate affiliates and consultants, and with third parties that perform a particular service on our behalf.

USE OF COOKIES

In cyberspace, cookies are pieces of information that a website transfers to an individual's hard drive for record-keeping purposes.  Cookies make Web surfing easier for you by saving your passwords, purchases and preferences while you're online. The use of cookies is an industry standard. You'll find them at most major web sites.

We reserve the right to use cookies to help us see which areas are popular and which are not. This helps us to target individuals with information and ads based on user interests, and also improve and update the Website based on such data as total number of users and pages viewed. This information is most easily tracked with cookies.

A cookie allows us to store the personal preferences that you set during each visit to the Website, which in turn allows us to speed up your future activities at the Website. Similarly, the stores hosted by the Website usually use cookies to track which products or services you've chosen to purchase while shopping. Letting cookies do the record keeping saves you the trouble of entering information over and over again. If you have registered and created an account via the App of on the Website, an identifying cookie will be placed on your computer. During future visits to the Website, we will only read and retrieve information that we set in a cookie during an earlier visit to the Website.

You may occasionally have cookies from our advertisers on the App or Website as well. We do not control these cookies, and they are not subject to our Privacy Policy. Advertisers do not have access to the App’s or Website’s cookies. The use of advertising cookies sent by third-party servers is standard in the Internet industry.

Most browsers are initially set to accept cookies. If you'd prefer, you can set yours to refuse cookies or to alert you when cookies are being sent. However, it is possible that some parts of the App or Website will not function properly if you do so.

International Users

This App and Website are hosted in the United States. If you are visiting from the European Union or other regions with laws governing data collection and use that may differ from United States law, please note that you are transferring your personal data to the United States and by providing your personal data you consent to that transfer and to our use of that information in accordance with this policy and you are submitting to U.S. jurisdiction and laws. When you provide personal data to us or our service providers or vendors, you consent to the processing of your data in the United States as the App and Website are operated and maintained exclusively in the United States.

YOU ACKNOWLEDGE THAT THE LAWS OF THE UNITED STATES TREAT YOUR INFORMATION IN A MANNER THAT MAY BE SUBSTANTIALLY DIFFERENT FROM, AND LESS PROTECTIVE THAN, THE TREATMENT REQUIRED UNDER THE LAWS OF OTHER COUNTRIES AND JURISDICTIONS. IF YOU DO NOT WANT YOUR INFORMATION TRANSFERRED TO THE UNITED STATES, YOU SHOULD NOT SHARE YOUR INFORMATION WITH US, OR MAKE USE OF THIS WEBSITE.  

YOU EXPRESSLY WAIVE ANY RIGHT YOU MAY HAVE TO REQUIRE US TO TREAT YOUR IDENTIFYING INFORMATION IN ACCORDANCE WITH THE LAWS OF ANY COUNTRY OR JURISIDICTION OTHER THAN THE UNITED STATES.  HOWEVER, THE FOREGOING WAIVER MAY NOT BE LEGALLY BINDING IN SOME COUNTRIES, SUCH AS THE MEMBER STATES OF THE EUROPEAN UNION.  TO THE EXTENT IT IS NOT LEGALLY BINDING IN THE COUNTRY IN WHICH YOU ARE LOCATED, THIS FOREGOING WAIVER DOES NOT APPLY TO YOU.

CONTACT

If you have any questions or concerns about our Privacy Policy or its implementation, you may contact us at general@theaphroditeapp.com.`;

export default privacyPolicyText;