const termsAndConditionsText = `This is a legal agreement ("Agreement") between you and Aphrodite Love Corp., a C corporation ("Aphrodite", “us”, “our”, or “we”), which may be contacted at general@theaphroditeapp.com. This Agreement applies to the access and use of the Aphrodite websites, including each website’s mobile and online versions (each, a “Website” or the “Websites”) and to the download and use of any of our applications (including iOS and Android applications) (the ”Applications”), and registration to or use of any of the services provided by us through the aforementioned platforms (collectively, with the Websites and Applications, each, a “Service” or the “Services”). By using any of the Services, you agree to, and are bound by, these terms and conditions of service of this Agreement (including, without limitation, the Privacy Policy) for as long as you continue to use the Services. IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, DO NOT USE THE SERVICES. Your use of, or participation in, certain Services may be subject to additional terms, and such terms will be either listed in this Agreement or will be presented to you for your acceptance when you sign up to use such Services and which are incorporated into and form part of this Agreement.
The Aphrodite Services consist of the following, without limitation: a Service for people seeking romantic relationships, a content Service such as Aphrodite Advice, containing articles about and related to relationships, and any additional services currently offered or which will be offered in the future by or on behalf of Aphrodite. Aphrodite may offer new services or revise any of the Services, at its discretion, and this Agreement will apply to all additional services or revised Services. Aphrodite also reserves the right to cease offering any of the Services.
This Agreement is subject to change by Aphrodite in its sole discretion at any time. We will notify you of any such changes by posting an updated version of the Agreement on this page. Your continued use of the Services after the posting of revisions to this Agreement will constitute your acceptance of such revisions. Please consult the end of this Agreement to determine when the Agreement was last revised.

 1. Eligibility.
a. Minimum Age. You must be at least 18 years old to register for the Services. By using any of the Services, you represent and warrant that you are at least 18 years old.

2. Use of the Services.
As a user of any of the Services (a "Registered User"), you agree to the following:
Basic Membership. It is free to register for the Services, which may be used by you at no cost (“Basic Membership”). You will be asked to register by providing preliminary information (including first and last names, pronouns, email address, phone number, birthdate, sexual orientation and password).  You may be asked to be asked to answer additional questions in the future.  
You acknowledge and agree that the information you provide as well as comprehensive statistical comparative data may be used by Aphrodite to automatically create your individual personality profile. 
You acknowledge and agree that your personality profile will then be integrated into the Aphrodite database. 

d. Access to Services and subscription using Non-Aphrodite Services. You may download the Aphrodite mobile Application using your Apple ID or Google account (each, a “Non-Aphrodite Service”) and use the Application on your iPhone or Android mobile device.
e. Exclusive Use. Your account is for your personal use only. You may not authorize others to use your account, and you may not assign or otherwise transfer your account to any other person or entity, except if previously expressly agreed to by us in writing. You acknowledge that Aphrodite is not responsible for third-party access to your account that results from theft or misappropriation of your usernames and passwords.
f. Geographic Limitations. The Services are intended for use in the United States and Canada. However, please note that Aphrodite may in the future provide the ability to register for the Services in certain other countries. Aphrodite reserves the right to not provide or stop providing the Services in any jurisdiction at any time in its sole discretion. You agree that you will only use the Services in a manner consistent with this Agreement and any and all applicable local, state, national and international laws and regulations, including, but not limited to, United States export control laws. By using the Services, you represent that you have not been designated by the United States government as a "Specially Designated National" or other person to whom the provisions of the Services are prohibited, and that you are not located in a country that is subject to embargo by the United States government. Registration for, and use of the Services is void where prohibited by any such laws or regulations. You are responsible for determining whether the use of the Services is legal in your jurisdiction.
g. Information Submitted. To the extent permitted by law, you are solely responsible for, and assume all liability regarding, (i) the information and content you input in connection with the Services; (ii) the information and content you post, transmit, publish, or otherwise make available (hereinafter "post") through the Services; and (iii) your interactions with other users through the Services. You warrant and represent that all information provided to Aphrodite through our Services or otherwise will be truthful, accurate, and complete, and will be submitted only for lawful purposes. Details of how Aphrodite may use information you provide or post which is personal to you are set out in our Privacy Policy which you hereby agree to as a condition of your usage of the Services, including, without lmitation, any and all apps we make available to you.
h. Risk Assumption and Precautions. You assume all risk when using the Services, including but not limited to all of the risks associated with any online or offline interactions with others, including dating. You agree to take all necessary precautions when meeting individuals through or as a result of your usage of the Services. In addition, you agree to review and follow the recommendations set forth in Aphrodite's Safety Tips, which is available at the bottom of all pages of the Services.
i. No Guarantees. You understand that Aphrodite makes no guarantees, either express or implied, regarding your ultimate success in meeting other individuals while using the Services or as to the conduct of any individuals you meet while using the Services.
 j. Reporting of Violations. You agree to promptly report to Aphrodite any violation of these terms and conditions or of any law your are aware of by others, including but not limited to, other users of the Services.
k. Content Removal. Aphrodite reserves the right, but has no obligation, to monitor any information or material you submit to the Services or post in the public areas of the Services. Aphrodite will have the right to remove any such information or material that in its sole opinion violates, or may violate, any applicable law or either the letter or spirit of this Agreement or upon the reasonable request of any third party. 
l. Posting and Communication Restrictions. You will not post, transmit or otherwise communicate to Aphrodite and its staff and outside service providers nor to other users of the Services, any content (or links thereto), or otherwise engage in any activity on, through or in connection with the Services and these Terms and Conditions, that:
i. promotes racism, bigotry, hatred or physical harm of any kind against any group or individual;
ii. is intended to or tends to abuse, harass, threaten or intimidate any other users of the Services;
iii. is defamatory, intentionally inaccurate, abusive, obscene, profane, offensive, sexually charged, obscene or otherwise objectionable or unlawful;
iv. infringes the intellectual property right of Aphrodite or any third party including copyright in and to content (e.g., music, movies, videos, photographs, images, software, literary works, etc.);
v. contains unauthorized use of video, audio photographs, or images of another person;
vi. promotes or enables illegal or unlawful activities, such as instructions on how to make or buy illegal weapons or drugs, violate someone's privacy, harm or harass another person, steal someone else’s identity, create or disseminate computer viruses, or circumvent copy-protect devices;
vii. is false or misrepresentative or otherwise intended to defraud, swindle or deceive other users of the Services;
viii. contains viruses, ransomware, spyware, adware, time bombs, trojan horses, cancelbots, worms or other harmful, or disruptive codes, components or devices;
ix. promotes or solicits involvement in or support of a political platform, religion, cult, or sect;
xii. disseminates another person's personal information without his or her permission, or collects or solicits another person's personal information for commercial or unlawful purposes;
xiii. is off-topic, meaningless, or otherwise intended to annoy or interfere with others' enjoyment of the Services;
xiv. impersonates, or otherwise misrepresents affiliation, connection or association with, any person or entity;
xv. solicits gambling or engages in any gambling or similar activity;
xvi. uses scripts, bots or other automated technology to access the Services;
xvii. uses the Services for chain letter, junk mail or spam e-mails;
xviii. collects or solicits personal information about anyone under 18; or
xix. is in any way used for or in connection with spamming, spimming, phishing, trolling, or similar activities.
m. No False Information. You will not provide inaccurate, misleading or false information to Aphrodite or to any other user of the Services. If information provided to Aphrodite or another user subsequently becomes inaccurate, misleading or false, you will promptly notify Aphrodite of such change.
n. No Advertising or Commercial Solicitation. You will not advertise or solicit any user to buy or sell any products or services on or through the Services. You may not transmit any chain letters, junk or spam e-mail to other users or other unsolicited commercial messages. Further, you will not use any information obtained from the Services in order to contact, advertise to, solicit, or sell to any user without their prior explicit consent. If you breach the terms of this subsection and send or post unsolicited bulk email, "spam" or other unsolicited communications of any kind through the Services, you acknowledge that you will have caused substantial harm to Aphrodite. To the extent permissible under applicable law, as a reasonable estimation of such harm, you agree to pay Aphrodite $100 USD for each such unsolicited communication you send through the Services.
o. Unique and Bona Fide Profile. As a Registered User of the Services, you will create only one unique profile. In addition, your use of the Services must be for bona fide purposes in order to maintain the integrity of the Services (for example, you may not become a Registered User solely to compile a report about the Services or to write a school research paper).  From time to time, however, Aphrodite retains the right to create test profiles in order to monitor the operation of the Services.
p. No Harassment of Aphrodite Employees or Agents. You will not harass, annoy, intimidate or threaten any Aphrodite employees or agents engaged in providing any portion of the Services to you.
q. Social Media. We may provide you the option to connect your Aphrodite account to your account on some social networking websites (such as via Continue with Facebook) for the purpose of logging in, uploading information or enabling certain features on the Service. When enabling this feature, we will disclose to you the information we collect from the connected social networking website, and will use such information in compliance with our Privacy Policy, the terms of which are binding on you and which you have agreed to by using the Services. By connecting your Aphrodite account to your account on any social networking website, you hereby consent to the continuous release of information about you to Aphrodite. We will not send any of your Aphrodite account information to the connected social networking website without first disclosing that to you. Each social network may further allow you to set privacy controls around your information on their system, and Aphrodite’s collection of information will be subject to such controls and permissions. This feature is subject to continuous change and improvement by us and each social networking website involved, and therefore the available features and shared information shall be subject to change in accordance with the terms of this Agreement, and the terms of use of the relevant social networking site.
r. Reverse Engineering and Non-Interference. In addition to any Aphrodite information or documents containing information that constitute a “trade secret” as that term is defined in the Uniform Trade Secrets Act as of September 16, 2015, the following will be deemed trade secrets of Aphrodite and you will treat the following as our trade secrets to the extent they have not been made public by us: 
(i) all source code, data and configuration files within or comprising our Services or used to receive content from, or deliver content to the Services, and all documentation relating thereto; 
(ii) all financial information relating to Aphrodite or its affiliates; 
(iii) all Service plans of Aphrodite or its affiliates. 
By consenting to the terms of this Agreement, you acknowledge and agree that such information has independent economic value due to it not being generally known or available to others, and that Aphrodite takes reasonable measures to protect the confidentiality and secrecy of such information. You agree not to, and warrant and represent that you will not, engage in any activity, assist any third party in engaging in any activity, or attempt in any way, or assist any third party in attempting in any way, to: 
(i) discover or use any trade secrets of Aphrodite without Aphrodite’s prior written consent;
(ii) reverse engineer or otherwise discover any source code utilized by our Services or any client or other software provided by us; or (vii) breach, discover, circumvent, disable or otherwise compromise any security, encryption, password protection, or other feature or mechanism used by us or our Services to protect the Services or any data, hardware, software or server used in connection with it.
s. Linking, crawling and framing. You agree not to, and warrant and represent that you will not assist any third party in engaging in any activity or attempting in any way, to reproduce, in whole or in part, any content provided by the Services through any method (including without limitation, through copying, caching or framing), unless such access is expressly permitted in a written agreement executed by Aphrodite and each and every individual whose personal information and/or work product is affected.

3. Proprietary Rights.
a. Ownership of Proprietary Information. You hereby acknowledge and agree that Aphrodite is the owner or licensee of highly valuable proprietary information accessible on or through the Services, including without limitation, the App as well as (collectively, "Confidential Information"). Aphrodite owns and hereby retains all proprietary rights in the Services, including but not limited to, all Confidential Information.
b. No Use of Confidential Information. You will not post, copy, modify, transmit, disclose, show in public, create any derivative works from, distribute, make commercial use of, or reproduce in any way any (i) Confidential Information; or (ii) other copyrighted material, trademarks, or other proprietary information accessible via the Services, without first obtaining the prior written consent of the owner of such proprietary rights.
c. Other Users' Information. Other users of the Services may post information, which has copyright protection whether or not it is identified as copyrighted. You agree that you shall keep confidential and will not copy, modify, publish, transmit, distribute, perform, display, commercially use, or sell any Aphrodite or third-party proprietary information available via the Services.
d. License to Posted or Accessed Content. By posting information or content to any profile pages or public area of the Services, or making it accessible to us by linking your Aphrodite account to any of your social network accounts (e.g. via Continue with Facebook) subject to applicable privacy laws as they relate to any personal information contained therein, you automatically grant, and you represent and warrant that you have the right to grant, to Aphrodite and its users, an irrevocable, perpetual, non-exclusive, fully-paid, worldwide license to use, reproduce, perform, publicly display, modify and distribute such information and content, and to prepare derivative works of, or incorporate into other works, such information and content, and to grant and authorize sub-licenses of the foregoing. From time to time, Aphrodite may create, test or implement new features or programs on the Services in which you may voluntarily choose to participate or may be a part of a test group with special access, in accordance with the additional terms and conditions of such features or programs. By your participation in such features or programs, you grant us the rights and waive certain other rights stated in this subsection in connection with the additional terms and conditions (if any) of such features or programs.
4. User Information.
a. Privacy Statement. By using the Services, you are consenting to the terms of Aphrodite's Privacy Policy.  We will only use your information in accordance with our Privacy Policy. You acknowledge that Aphrodite may transfer your personal information to Aphrodite's and its affiliated companies’ offices overseas and may share your personal information with third parties employed to provide some or all of the Services. By registering to use the Services, you consent to this transfer of your personal information. For information about the collection, use and possible disclosure of information and material provided by you, please click on Aphrodite's Privacy Policy located on the Services. 
b. Disclosure By Law. You acknowledge and agree that Aphrodite may disclose information you provide in accordance with our Privacy Policy, including, if required to do so by law, at the request of certain third parties, or if we, in our sole discretion, believe that disclosure is reasonable to (1) comply with the law, requests or orders from law enforcement, or any legal process (whether or not such disclosure is required by applicable law); (2) protect or defend Aphrodite's, or a third party's, rights or property; or (3) protect someone's health or safety, such as when harm or violence against any person (including the user) is threatened.
c. Disclosure to Protect Abuse Victims. Notwithstanding any other provision of this Agreement or the Privacy Policy, Aphrodite reserves the right, but has no obligation, to disclose any information that you submit to the Services, if in its sole opinion, Aphrodite suspects or has reason to suspect, that the information involves a party who may be the victim of abuse in any form. Abuse may include, without limitation, elder abuse, child abuse, spousal abuse, neglect, or domestic violence. Information, including personal information, may be disclosed to authorities that Aphrodite, in its sole discretion, deems appropriate to handle such disclosure, provided that such disclosure is pursuant to applicable law. Appropriate authorities may include, without limitation, law enforcement agencies, child protection agencies, or court officials. You hereby acknowledge and agree that Aphrodite is permitted to make such disclosure.
d. Use of Anonymous Information for Research. As set forth in our Privacy Policy, by using the Services, you agree to allow Aphrodite to anonymously license, sell and otherwise use the information from you and your experiences through the Services to continue Aphrodite's research into relationships and to improve the Services. This research, conducted by psychologists and behavior research scientists, may be published in academic journals. However, your responses will be anonymous, and we will not publish research containing your personal identifying information.
5. Links to Third-Party Websites / Dealings with Advertisers and Sponsors.
The Services do not currently advertise any third-party goods or services and do not contain links to third-party websites. However, Aphrodite reserves its rights to advertise on the Services and include third-party website links on the Services, including without limitation, advertisers, which are not under the control of Aphrodite, and Aphrodite is not responsible for the content of any linked website or any link contained in a linked website, or any changes or updates to such websites. Aphrodite provides these links to you only as a convenience, and the inclusion of any link does not imply that Aphrodite endorses or accepts any responsibility for the content on such third-party website. Your correspondence or business dealings with, or participation in promotions of, advertisers or sweepstakes or other promotion sponsors found on or through the Services (including payment and delivery of related goods or services, any personal information or opt-in contact information voluntarily given to advertisers and sweepstake sponsors, and any other terms, conditions, warranties or representations associated with such dealings) are solely between you and such advertiser or sweepstakes or promotion sponsor. You agree that Aphrodite will not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings, including the sharing of the information you supply to Aphrodite with advertisers or sweepstakes or promotion sponsors, or as the result of the presence of such advertisers on the Services. Please visit our Privacy Policy to learn more about our personal information handling practices.
 
 6. Disclaimer of Warranties and Conditions.
a. No Warranties or Conditions. THIS SECTION WILL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW AND SUBJECT ALWAYS TO CLAUSE 7 (LIMITATION OF LIABILITY) BELOW. APHRODITE PROVIDES THE SERVICES ON AN "AS IS" AND "AS AVAILABLE" BASIS AND MAKES NO AND DISCLAIMS ALL REPRESENTATIONS, WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, COLLATERAL OR OTHERWISE WITH RESPECT TO THE SERVICES (INCLUDING ALL CONTENT AND INFORMATION CONTAINED THEREIN), INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. APHRODITE DOES NOT REPRESENT OR WARRANT THAT YOUR USE OF THE SERVICES WILL BE SECURE, UNINTERRUPTED, ALWAYS AVAILABLE, FREE OF ERRORS, VIRUSES, BUGS OR OTHER HARMFUL COMPONENTS, OR WILL MEET YOUR REQUIREMENTS, OR THAT ANY DEFECTS IN THE SERVICES WILL BE CORRECTED. APHRODITE DISCLAIMS LIABILITY FOR, AND NO REPRESENTATION, WARRANTY OR CONDITION IS MADE WITH RESPECT TO, THE CONNECTIVITY AND AVAILABILITY OF THE SERVICES. WITHOUT LIMITING THE FOREGOING, YOU ACKNOWLEDGE AND AGREE THAT NO SOFTWARE OR WEBSITE CAN BE ENTIRELY SECURE OR FREE OF RISK OF SECURITY BREACHES OR ATTACKS BY THIRD PARTIES, AND THAT WE MAKE NO WARRANTY OR REPRESENTATION THAT OUR SERVICES WILL BE SECURE OR FREE FROM DATA BREACHES OR CYBER ATTACKS.
b. Third Party Content. Opinions, advice, statements, offers, or other information or content made available through the Services, but not directly by Aphrodite, are those of their respective authors, and should not necessarily be relied upon. Such authors are solely responsible for such content. APHRODITE DOES NOT: (i) GUARANTEE THE ACCURACY, COMPLETENESS OR USEFULNESS OF ANY INFORMATION PROVIDED ON OR ACCESSED VIA THE SERVICES, OR (ii) ADOPT, ENDORSE OR ACCEPT RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE, OR STATEMENT MADE BY ANY PARTY OTHER THAN APHRODITE. TO THE FULLEST EXTENT PERMITTED BY LAW, UNDER NO CIRCUMSTANCES WILL APHRODITE BE RESPONSIBLE FOR ANY LOSS OR DAMAGE RESULTING FROM ANYONE'S RELIANCE ON INFORMATION OR OTHER CONTENT POSTED ON THE SERVICES, OR TRANSMITTED TO OR BY ANY USERS.
c. Beta Features. From time to time, Aphrodite may offer new "beta" features or tools with which its users may experiment on the Services. Such features or tools are offered solely for experimental purposes and without any representation, warranty or conditions of any kind, and may be modified or discontinued at Aphrodite's sole discretion. The provisions of this Disclaimer of Warranties and Conditions section apply with full force to such features or tools.

 7. Limitation of Liability.
a. Limitation of Damages and Aggregate Liability. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL APHRODITE BE LIABLE FOR ANY DAMAGES WHATSOEVER, WHETHER DIRECT, INDIRECT, GENERAL, SPECIAL, COMPENSATORY, CONSEQUENTIAL, PUNITIVE, EXEMPLARY AND/OR INCIDENTAL DAMAGES ARISING OUT OF OR RELATING TO THE USE OR INABILITY TO USE THE SERVICES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OR CORRUPTION OF DATA OR PROGRAMS, SERVICE INTERRUPTIONS AND PROCUREMENT OF SUBSTITUTE SERVICES, EVEN IF APHRODITE KNOWS OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES WILL APHRODITE'S AGGREGATE LIABILITY, IN ANY FORM OF ACTION WHATSOEVER IN CONNECTION WITH THIS AGREEMENT OR THE USE OF THE SERVICES , EXCEED THE PRICE PAID BY YOU FOR YOUR ACCOUNT, OR, IF YOU HAVE NOT PAID APHRODITE FOR THE USE OF ANY SERVICES, THE AMOUNT OF USD $25.00 OR ITS EQUIVALENT.
b. No Liability for non-Aphrodite Actions. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL APHRODITE BE LIABLE FOR ANY DAMAGES WHATSOEVER, WHETHER PUNITIVE, EXEMPLARY, DIRECT, INDIRECT, GENERAL, SPECIAL, COMPENSATORY, CONSEQUENTIAL, AND/OR INCIDENTAL, ARISING OUT OF OR RELATING TO THE CONDUCT OF YOU OR ANYONE ELSE IN CONNECTION WITH THE USE OF THE SERVICES, INCLUDING WITHOUT LIMITATION, BODILY INJURY, DEATH, EMOTIONAL DISTRESS, AND/OR ANY OTHER DAMAGES RESULTING FROM COMMUNICATIONS OR MEETINGS WITH OTHER REGISTERED USERS OF THE SERVICES. THIS INCLUDES ANY CLAIMS, LOSSES OR DAMAGES ARISING FROM THE CONDUCT OF USERS WHO HAVE REGISTERED UNDER FALSE PRETENSES OR WHO ATTEMPT TO DEFRAUD OR HARM YOU.
c. Information Verification. Aphrodite may but is not required to use various ways of verifying information that users have provided. However, none of those ways are perfect, and you agree that Aphrodite will have no liability to you arising from any incorrectly verified information.  You acknowledge that Aphrodite does not verify information unless and until Aphrodite is notified of doubts about accuracy by and outside third-party.
8. Indemnification.
a. To the maximum extent permitted by law, you agree to indemnify, defend and hold harmless Aphrodite and its affiliates and/or related entities, whether direct or indirect, current, former or future, and its and their respective current, former or future officers, directors, employees, agents, successors and assigns and related third parties (each an “Indemnified Party”), for any claims, causes of action, debts, damages, losses, costs, liabilities and expenses (including reasonable attorneys’ fees) relating to or arising out of any third party claim that related to: (a) your use of or inability to use the Services, (b) any user postings made by you, (c) your violation of any terms of this Agreement or your violation of any rights of a third party, or (d) your violation of any applicable laws, rules or regulations, except to the extent caused by any unlawful or negligent act or omission by Aphrodite. Aphrodite reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with Aphrodite in asserting any available defenses. An Indemnified Party may participate in the defense by counsel of its own choosing, at its own cost and expense. You shall not settle any claim that adversely affects an Indemnified Party or imposes any obligation or liability on an Indemnified Party without the Indemnified Party’s prior written consent.
b. TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOU HEREBY RELEASE EACH INDEMNIFIED PARTY FROM ALL DAMAGES (WHETHER DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR OTHERWISE), LOSSES, LIABILITIES, COSTS AND EXPENSES OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN CONNECTION WITH DISPUTES BETWEEN YOU AND THIRD PARTIES CONCERNING THE SERVICES OR THIS AGREEMENT. IN CONNECTION WITH THE FOREGOING RELEASE, YOU HEREBY WAIVE (TO THE MAXIMUM EXTENT PERMITTED BY LAW) CALIFORNIA CIVIL CODE 1542 (AND ANY OTHER APPLICABLE LAW OR STATUTE) WHICH SUBSTANTIALLY STATES:
“A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.”
9. Law Enforcement Contact.
Law enforcement officials may send correspondence (such as subpoenas, court orders and warrants) to Aphrodite to our facsimile number at +1-424-249-7285. All other correspondence sent to this facsimile number will be discarded.
10. Communication and Privacy.
We may use the email address associated with your account to send you messages, including notifications of important changes to the Services, special offers, or attempts to collect monies owed. Further, we may contact you by telephone in order to communicate with you regarding the Services. If you do not want to receive certain email messages or telephone calls (including at any wireless number you may have voluntarily provided us), please refer to our Privacy Policy to review your options.
11. Term and Termination.
This Agreement will become effective upon your acceptance of the Agreement by your use of the Services and will remain in effect in perpetuity unless terminated hereunder.
Either you or Aphrodite may terminate your account at any time, for any reason or no reason, without explanation, effective upon sending written notice to the other party. Aphrodite reserves the right to immediately suspend or terminate your access to any of the Services, without notice, for any reason or no reason. We also reserve the right to remove your account information or data from our Services and any other records if your account and/or access to the Services is terminated. In the event your access to any of the Services is suspended due to a material breach of this Agreement, you agree that all fees, if any, paid to Aphrodite by you are nonrefundable and that any outstanding fees (e.g., remaining installments) will become due and payable immediately. You may terminate your account by following the steps in the applicable section under "Cancellations" below, or by sending a notice of cancellation to: Aphrodite, Inc., Attn: Emi Knight. Following any termination of your Services account due to a violation of our Agreement, Aphrodite may, at our discretion or as required by law, send a notice thereof to other users with whom you have corresponded for the protection of our members.

14. Governing Law & Venue
Unless prohibited by local law, this Agreement is governed by the laws of the State of Texas, without giving effect to any principles of conflicts of laws. Notwithstanding the foregoing, Section 15 of this Agreement shall be governed by the Federal Arbitration Act. Nothing in this Agreement is intended to limit a party’s right to seek equitable relief at any time. If the Arbitration Agreement (as set forth in Section 15) is held to be unenforceable, you agree that any claims or disputes that you have against us must be resolved in the federal or state courts located in Los Angeles, CA to the extent permissible by applicable law. Notwithstanding the foregoing, claims appropriately brought in small claims court may be filed in any court of competent jurisdiction. For the sake of clarity, the choice of California law shall not exclude, limit or supersede a consumer’s rights or remedies under mandatory consumer protection laws in the jurisdiction where the consumer resides.
15. Arbitration Agreement, Class Action Waiver and Jury Trial Waiver.
a. Purpose: This section 15 of the Agreement (henceforth referred to as “Arbitration Agreement”) facilitates the prompt and efficient resolution of any Disputes that may arise between you and Aphrodite. Arbitration is a form of private Dispute (as defined below) resolution in which parties to a contract agree to submit their Disputes and potential Disputes to a neutral third person (called an arbitrator) for a binding decision, instead of having such Dispute(s) decided in a lawsuit, in court, by a judge or jury trial.
Please read this Arbitration Agreement carefully. It provides that all Disputes between you and Aphrodite shall be resolved by binding arbitration. Arbitration replaces the right to go to court. In the absence of this Arbitration Agreement, you may otherwise have a right or opportunity to bring claims in a court, before a judge or jury, and/or to participate in or be represented in a case filed in court by others (including, but not limited to, class actions). Entering into this Arbitration Agreement constitutes a waiver of your right to litigate claims in court and all opportunity to be heard by a judge or jury. There is no judge or jury in arbitration, and court review of an arbitration award is limited. The arbitrator must follow this Arbitration Agreement and can award the same damages and relief as a court (including attorney’s fees, if otherwise authorized by applicable law).
For the purpose of this Arbitration Agreement, “Aphrodite” means Aphrodite, Inc. and its parents, subsidiaries, and affiliated companies, and each of their respective officers, directors, employees, and agents. The term “Dispute” means any dispute, claim, or controversy between you and Aphrodite regarding any aspect of your relationship with Aphrodite, whether based in contract, statute, regulation, ordinance, tort (including, but not limited to, fraud, misrepresentation, fraudulent inducement, negligence, gross negligence or reckless behavior), or any other legal or equitable theory, and includes the validity, enforceability or scope of this Arbitration Agreement (with the exception of the enforceability of the Class Action Waiver in this Arbitration Agreement). “Dispute” is to be given the broadest possible meaning that will be enforced.
YOU AND APHRODITE EACH AGREE THAT, EXCEPT AS PROVIDED BELOW, ANY AND ALL DISPUTES, AS DEFINED ABOVE, WHETHER PRESENTLY IN EXISTENCE OR BASED ON ACTS OR OMISSIONS IN THE PAST OR IN THE FUTURE, WILL BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION RATHER THAN IN COURT IN ACCORDANCE WITH THIS ARBITRATION AGREEMENT.
b. Pre-Arbitration Dispute Resolution: For all Disputes you must first give Aphrodite an opportunity to resolve the Dispute. You must commence this process by emailing general@theaphroditeapp.com.. That written notification must:
include (1) your name, (2) your address, (3) a written description of the Dispute, and (4) a description of the specific relief you seek. If Aphrodite does not resolve the Dispute to your satisfaction within 45 days after it receives your written notification, you may pursue your Dispute in arbitration.
c. Arbitration Procedures: If this Arbitration Agreement applies and the Dispute is not resolved as provided above (“Pre-Arbitration Claim Resolution”) either you or Aphrodite may initiate arbitration proceedings. The American Arbitration Association
(“AAA”), www.adr.org will arbitrate all Disputes, and the arbitration will be conducted before a single arbitrator. The arbitration shall be commenced as an individual arbitration, and shall in no event be commenced as a representative or class arbitration. All issues shall be for the arbitrator to decide, including the scope of this Arbitration Agreement.
For arbitration before the AAA, for Disputes of less than $75,000 USD, the AAA’s Consumer Arbitration Rules will apply; for Disputes involving $75,000 USD or more, the AAA’s Commercial Arbitration Rules will apply. In either instance, the AAA’s Optional Rules For Emergency Measures Of Protection shall apply. The AAA rules are available at www.adr.org or by calling 1-800-778-7879. This Arbitration Agreement governs in the event it conflicts with the applicable arbitration rules. Under no circumstances will class action procedures or rules apply to the arbitration.
Because your contract with Aphrodite, the Agreement, and this Arbitration Agreement concern interstate commerce, the Federal Arbitration Act (“FAA”) governs the arbitrability of all Disputes. However, the arbitrator will apply applicable substantive law consistent with the FAA and the applicable statute of limitations or condition precedent to suit.
d. Arbitration Award: The arbitrator may award on an individual basis any relief that would be available pursuant to applicable law, and will not have the power to award relief to, against or for the benefit of any person who is not a party to the proceeding. The arbitrator shall make any award in writing but need not provide a statement of reasons unless requested by a party. Such award by the arbitrator will be final and binding on the parties, except for any right of appeal provided by the FAA, and may be entered in any court having jurisdiction over the parties for purposes of enforcement.
e. Location of Arbitration: You may initiate arbitration in Los Angeles, CA, via written submissions, in the federal judicial district that includes your address that you provide in your written notification of Pre-Arbitration Dispute Resolution, or in another location mutually agreed to by the parties.
f. Payment of Arbitration Fees and Costs: Absent a finding that your demand is frivolous, brought for an improper purpose, or malicious as set forth by the standards of Federal Rule of Civil Procedure 11(b), Aphrodite will pay all arbitration filing fees and arbitrator’s costs and expenses upon your written request given prior to the commencement of the arbitration. You are responsible for all additional fees and costs that you incur in the arbitration, including, but not limited to, attorneys or expert witnesses. Fees and costs may be awarded as provided pursuant to applicable law. In addition to any rights to recover fees and costs under applicable law, if you provide notice and negotiate in good faith with Aphrodite as provided in the section above titled “Pre-Arbitration Dispute Resolution” and the arbitrator concludes that you are the prevailing party in the arbitration, you will be entitled to recover from Aphrodite your actual and reasonable attorney’s fees and costs as determined by the arbitrator.
g. Class Action Waiver: The parties agree that the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a class or representative proceeding or claims (such as a class action, representative action, consolidated action or private attorney general action) unless both you and Aphrodite specifically agree in writing to do so following initiation of the arbitration. Neither you, nor any other Registered Member of Aphrodite and/or user of Aphrodite services, can be a class representative, class member, or otherwise participate in a class, representative, consolidated or private attorney general proceeding.
h. Limitation of Procedural Rights: You understand and agree that, by entering into this Arbitration Agreement, you and Aphrodite are each agreeing to arbitration instead of the right to a trial before a judge or jury in a public court. In the absence of this Arbitration Agreement, you and Aphrodite might otherwise have had a right or opportunity to bring Disputes in a court, before a judge or jury, and/or to participate or be represented in a case filed in court by others (including class actions). You give up those rights. Other rights that you would have if you went to court, such as the right to appeal and to certain types of discovery, may be more limited in arbitration. The right to appellate review of an arbitrator’s decision is much more limited than in court, and in general an arbitrator’s decision may not be appealed for errors of fact or law.
i. Severability: If any clause within this Arbitration Agreement (other than the Class Action Waiver clause above) is found to be illegal or unenforceable, that clause will be severed from this Arbitration Agreement, and the remainder of this Arbitration Agreement will be given full force and effect. If the Class Action Waiver clause is found to be illegal or unenforceable, then this entire Arbitration Agreement will be unenforceable, and the Dispute will be decided by a court.
j. Continuation: This Arbitration Agreement shall survive the termination of your contract with Aphrodite and your use of Aphrodite Services.
16. General Provisions.
a. Right to Seek Injunction. Violation of this Agreement may cause Aphrodite irreparable harm, and therefore agree that Aphrodite will be entitled to seek extraordinary relief in court, including but not limited to temporary restraining orders, preliminary injunctions and permanent injunctions without the necessity of posting a bond or other security, in addition to and without prejudice to any other rights or remedies that Aphrodite may have for a breach of this Agreement.
b. Miscellaneous. This Agreement, which you accept upon registration for the Services, the Privacy Policy located on the Services, and any applicable payment, renewal, additional Services terms, comprise the entire agreement between you and Aphrodite regarding the use of this Service, superseding any prior agreements between you and Aphrodite related to your use of the Services (including, but not limited to, any prior versions of this Agreement). The FAQ's found on the Services are for informational purposes only and are not deemed to be part of this Agreement. Unless otherwise explicitly stated, the Agreement will survive termination of your registration to the Services. The failure of Aphrodite to exercise or enforce any right or provision of this Agreement does not constitute a waiver of such right or provision. If any provision of this Agreement is held invalid, the remainder of this Agreement will continue in full force and effect. The section titles in this Agreement are for convenience only and have no legal or contractual effect.
17. Digital Millennium Copyright Act Notice.
If you believe that your copyrighted work has been copied in a way that constitutes copyright infringement and is accessible via the Services, please notify Aphrodite's copyright agent, as set forth in the Digital Millennium Copyright Act of 1998 (DMCA). For your complaint to be valid under the DMCA, you must provide the following information in writing:
An electronic or physical signature of a person authorized to act on behalf of the copyright owner;
Identification of the copyrighted work that you claim is being infringed;
Identification of the material that is claimed to be infringing and where it is located on the Services;
Information reasonably sufficient to permit Aphrodite to contact you, such as your address, telephone number, and email address;
A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or law; and
A statement, made under penalty of perjury, that the above information is accurate, and that you are the copyright owner or are authorized to act on behalf of the owner.

18. Revision Date.
This Agreement was last revised on November 21st, 2022.
COPYRIGHT NOTICE:
Copyright © 2022 Aphrodite Love Corp. All Rights Reserved. Aphrodite and other marks, colors, and images are registered and common law trademarks of Aphrodite, Inc. Other trademarks and brands are the property of their respective owners.`;

export default termsAndConditionsText;